###
POST http://localhost:8181/route
Content-Type: application/json

{
  "name": "Restauradores",
  "stops": [
    {
      "name": "Benfica",
      "sequence": 1,
      "coordinate": {
        "latitude": 38.746381,
        "longitude": -9.190099
      }
    },
    {
      "name": "Rossio",
      "sequence": 2,
      "coordinate": {
        "latitude": 38.714249,
        "longitude": -9.139337
      }
    }
  ],
  "vehicleId": "0b7be231-dd72-43f5-9a13-0efb346280eb"
}