services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: route-manager
        MONGO_INITDB_ROOT_PASSWORD: route-manager
        MONGO_INITDB_DATABASE: route-manager

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://route-manager:route-manager@mongo:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: route-manager
      ME_CONFIG_MONGODB_ADMINPASSWORD: route-manager
      ME_CONFIG_BASICAUTH: false
